#!/usr/bin/env python3
#Secure chat interceptor
import socket
import sys
import time
from _thread import *
from datetime import datetime
import threading
import subprocess
import argparse
import ssl

PORT = 7129
RECVSIZE = 1024


if __name__ == '__main__':

    if len(sys.argv) != 2 and len(sys.argv) != 3:
        print("Usage : {0} -s \n\t{0} -c <hostname>".format(sys.argv[0]))
        sys.exit(1)
    if sys.argv[1] == '-s':
        server()
    elif sys.argv[1] == '-c' and len(sys.argv) == 3:
        print("This is client connecting to {}".format(sys.argv[2]))
        client(sys.argv[2])
    else:
        print("Usage : {0} -s \n\t{0} -c <hostname>".format(sys.argv[0]))
        sys.exit(1)
    
    
